### ISSUE TITLE
This seems to be for version 1.15.2

### ISSUE THREAD

**Issue by mechanicAS** [TechnoVisionDev/Forge-Modding-Tutorial-1.16#2]
I built the project and loaded into mc 1.16.1, but launcher failed saying this mod is for 1.15.2

**Comment by shubhayshah** [comment]
@mechanicAS in Youtube TechnoVision had a video where he was updating TO 1.16.1 Forge-maybe you need to update it yourself?  What are your thoughts, @TechnoVisionDev? 

Github user, @shubhayshah

**Comment by YodaForce157** [comment]
hmm you may need to re-install it
