### ISSUE TITLE
Error when updating to 1.16.1

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [TechnoVisionDev/Forge-Modding-Tutorial-1.16#3]
it makes errors when updating to 1.16.1

**Comment by gulab9762** [comment]
I downloaded forge for 1.16.2 and copy version and forge data from it and then pasted it to 1.15.2 build.gradle. This worked for me while upgrading to 1.16.2.
You might be looking for this:
version:'20200514-1.16'
forge:1.16.2-33.0.61
